all:
  hosts:
    app_server:
      ansible_host: 98.80.21.98
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ../terraform/wt-key

    monitoring_server:
      ansible_host: 13.220.141.0
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ../terraform/mon-key
