#SPDX-License-Identifier: MIT-0
---
# tasks file for app
- name: Login to ECR
  shell: |
    aws ecr get-login-password --region us-east-1 \
    | docker login --username AWS --password-stdin "{{ ecr_repo }}"

- name: Pull app image
  docker_image:
    name: "{{ ecr_repo }}:{{ image_tag }}"
    source: pull

- name: Run app container
  docker_container:
    name: flask_app
    image: "{{ ecr_repo }}:{{ image_tag }}"
    state: started
    restart_policy: always
    ports:
      - "5000:5000"
    env:
      DB_HOST: "{{ db_host }}"
      DB_USER: "{{ db_user }}"
      DB_PASSWORD: "{{ db_password }}"
      DB_NAME: "{{ db_name }}"
      DB_PORT: "5432"
      # DATABASE_URL: "postgresql://{{ db_user }}:{{ db_password }}@{{ db_host }}:5432/{{ db_name }}"
      DATABASE_URL: "postgresql://{{ db_user }}:{{ db_password }}@{{ db_host }}/{{ db_name }}"
      # That output from aws_db_instance.postgres.endpoint already includes :5432 and was causing :5432:5432
